version: '3.8'

services:
  broker1:
    build:
      context: ./broker  # Directory containing Dockerfile for broker
      dockerfile: Dockerfile  # Ensure Dockerfile is explicitly referenced if needed
    container_name: broker1
    ports:
      - "3000:3000"  # Expose port 3000 to the host
    environment:
      BROKER_ID: 1
      PORT: 3000
      PEERS: "2,3"
    command: ["python", "broker.py", "--broker_id", "1", "--port", "3000", "--peers", "2,3"]

  broker2:
    build:
      context: ./broker  # Directory containing Dockerfile for broker
      dockerfile: Dockerfile
    container_name: broker2
    ports:
      - "3001:3001"  # Expose port 3001 to the host
    environment:
      BROKER_ID: 2
      PORT: 3001
      PEERS: "1,3"
    command: ["python", "broker.py", "--broker_id", "2", "--port", "3001", "--peers", "1,3"]

  broker3:
    build:
      context: ./broker  # Directory containing Dockerfile for broker
      dockerfile: Dockerfile
    container_name: broker3
    ports:
      - "3002:3002"  # Expose port 3002 to the host
    environment:
      BROKER_ID: 3
      PORT: 3002
      PEERS: "1,2"
    command: ["python", "broker.py", "--broker_id", "3", "--port", "3002", "--peers", "1,2"]

  client:
    build:
      context: ./client  # Directory containing Dockerfile for client
      dockerfile: Dockerfile
    container_name: newspubsub-client
    ports:
      - "8080:8080"  # Expose port 8080 to the host
    command: ["python", "client_interface.py"]
