version: '3.8'

services:
  broker1:
    build: ./broker
    container_name: broker1
    environment:
      - BROKER_ID=1
      - PEERS=2,3,4,5
    ports:
      - "8081:8080"

  broker2:
    build: ./broker
    container_name: broker2
    environment:
      - BROKER_ID=2
      - PEERS=1,3,4,5
    ports:
      - "8082:8080"

  broker3:
    build: ./broker
    container_name: broker3
    environment:
      - BROKER_ID=3
      - PEERS=1,2,4,5
    ports:
      - "8083:8080"

  broker4:
    build: ./broker
    container_name: broker4
    environment:
      - BROKER_ID=4
      - PEERS=1,2,3,5
    ports:
      - "8084:8080"

  broker5:
    build: ./broker
    container_name: broker5
    environment:
      - BROKER_ID=5
      - PEERS=1,2,3,4
    ports:
      - "8085:8080"
